spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/sessia
    password: 154263789
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath*:database/init.sql
      data-locations: classpath*:database/data.sql